steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/ia-agentes-15/repositorio-backend-langchain-inmobiliaria/imagen-v2-backend-langchain-inmobiliaria-k:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ia-agentes-15/repositorio-backend-langchain-inmobiliaria/imagen-v2-backend-langchain-inmobiliaria-k:latest']
